[build-system]
requires = ['setuptools']
build-backend = 'setuptools.build_meta'

[project]
name = 'mplgz2ingested'
version = '0.0.1'
dependencies = [
    'mpl2nc',
    'xarray',
    'numpy',
    'netCDF4'
]

[tool.setuptools.packages.find]
exclude = ['*.sh','*.cdf']